language: node_js
node_js:
  - "8.9.4"

script:
  - npm run-script build
  - npm test

before_deploy:
  - sed -i '/web/d' .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: web
  github_token: $GITHUB_API_KEY
  target-branch: gh-pages
  on:
    branch: dev
